import { NavBar } from "@/components/navbar";
import { Metadata } from "next/types";

export const metadata: Metadata = {
  title: "Web3 app",
  description: "Generated by create next app",
};

const HomeLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <main>
      <NavBar />
      {children}
    </main>
  );
};

export default HomeLayout;
